apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_2.name }}
  labels:
    app: {{ template "helloworld-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      greeting: hello
      department: world
  type: {{ .Values.service_2.type }}
  ports:
    - port: {{ .Values.service_2.internalPort }}
      targetPort: {{ .Values.service_2.externalPort }}
      protocol: TCP
      name: {{ .Values.service_2.name }}
  selector:
    app: {{ template "helloworld-chart.name" . }}
    release: {{ .Release.Name }}
