apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service_1.name }}
  labels:
    app: {{ template "helloworld-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "helloworld-chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      selector:
        matchLabels:
          greeting: hello
          department: kubernetes
      containers:
        - name: {{ .Values.service_1.name }}
          image: "gcr.io/google-samples/node-hello:1.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "PORT"
            value: "{{ .Values.service_1.externalPort }}"