{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "helloworld-chart.fullname" . -}}
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: {{ template "helloworld-chart.fullname" . }}
  labels:
    app: {{ template "helloworld-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: {{ .Values.ingress.app1_path }} 
            backend:
              serviceName: {{ .Values.service_1.name }}
              servicePort: {{ .Values.service_1.internalPort }}
          - path: {{ .Values.ingress.app2_path }} 
            backend:
              serviceName: {{ .Values.service_2.name }}
              servicePort: {{ .Values.service_2.internalPort }}

  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
